export const conferences = [
    { value: "ACC", label: "ACC", logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/500/1.png" },
    { value: "AMERICAN", label: "American", logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/500/151.png" },
    { value: "BIG_12", label: "Big 12", logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/500/4.png" },
    { value: "BIG_TEN", label: "Big Ten", logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/500/5.png" },
    { value: "FBS_INDEPENDENT", label: "FBS Independent", logo: "https://logos-world.net/wp-content/uploads/2025/01/Division-I-FBS-Independents-Logo-500x281.png" },
    { value: "MAC", label: "MAC", logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/500/15.png" },
    { value: "MOUNTAIN_WEST", label: "Mountain West", logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/500/17.png" },
    { value: "PAC_12", label: "Pac-12", logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/500/9.png" },
    { value: "SEC", label: "SEC", logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/500/8.png" },
    { value: "SUN_BELT", label: "Sun Belt", logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/500/37.png" },
    { value: "MISSOURI_VALLEY", label: "Missouri Valley", logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/500/21.png" },
    { value: "COLONIAL", label: "Colonial", logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/500/48.png" },
    { value: "NEC", label: "NEC", logo: "https://a.espncdn.com/i/teamlogos/ncaa_conf/500/25.png" },
];