export const conferences = [
    { value: "ACC", label: "ACC" },
    { value: "AMERICAN", label: "American" },
    { value: "BIG_12", label: "Big 12" },
    { value: "BIG_TEN", label: "Big Ten" },
    { value: "CUSA", label: "C-USA" },
    { value: "FBS_INDEPENDENT", label: "FBS Independent" },
    { value: "MAC", label: "MAC" },
    { value: "MOUNTAIN_WEST", label: "Mountain West" },
    { value: "PAC_12", label: "Pac-12" },
    { value: "SEC", label: "SEC" },
    { value: "SUN_BELT", label: "Sun Belt" },
    { value: "ATLANTIC_SUN", label: "Atlantic Sun" },
    { value: "BIG_SKY", label: "Big Sky" },
    { value: "CAROLINA_FOOTBALL_CONFERENCE", label: "Carolina Football Conference" },
    { value: "MISSOURI_VALLEY", label: "Missouri Valley" },
    { value: "COLONIAL", label: "Colonial" },
    { value: "NEC", label: "NEC" },
    { value: "IVY_LEAGUE", label: "Ivy League" },
    { value: "MID_ATLANTIC", label: "Mid-Atlantic" },
    { value: "SOUTHLAND", label: "Southland" },
    { value: "OHIO_VALLEY", label: "Ohio Valley" },
    { value: "SWAC", label: "SWAC" },
];