export const conferences = [
    { value: "ACC", label: "ACC" },
    { value: "AMERICAN", label: "American" },
    { value: "BIG_12", label: "Big 12" },
    { value: "BIG_TEN", label: "Big Ten" },
    { value: "FBS_INDEPENDENT", label: "FBS Independent" },
    { value: "MAC", label: "MAC" },
    { value: "MOUNTAIN_WEST", label: "Mountain West" },
    { value: "PAC_12", label: "Pac-12" },
    { value: "SEC", label: "SEC" },
    { value: "SUN_BELT", label: "Sun Belt" },
    { value: "MISSOURI_VALLEY", label: "Missouri Valley" },
    { value: "COLONIAL", label: "Colonial" },
    { value: "NEC", label: "NEC" },
];