export const STAT_GROUPS = [
    ['Passing', [
        { label: 'Pass yards', key: 'pass_yards', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Pass attempts', key: 'pass_attempts', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Pass completions', key: 'pass_completions', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Completion %', key: 'pass_completion_percentage', fmt: 'pct', opp: true, agg: 'rate', num: 'pass_completions', den: 'pass_attempts' },
        { label: 'Pass success %', key: 'pass_success_percentage', fmt: 'pct', opp: true, agg: 'rate', num: 'pass_successes', den: 'pass_attempts' },
        { label: 'Passing touchdowns', key: 'pass_touchdowns', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Longest pass', key: 'longest_pass', fmt: 'num', opp: true, agg: 'max' },
        { label: 'Sacks allowed', key: 'sacks_allowed', fmt: 'num', agg: 'sum' },
    ]],
    ['Rushing', [
        { label: 'Rush yards', key: 'rush_yards', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Rush attempts', key: 'rush_attempts', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Rush success %', key: 'rush_success_percentage', fmt: 'pct', opp: true, agg: 'rate', num: 'rush_successes', den: 'rush_attempts' },
        { label: 'Rushing touchdowns', key: 'rush_touchdowns', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Longest run', key: 'longest_run', fmt: 'num', opp: true, agg: 'max' },
    ]],
    ['Offense', [
        { label: 'Total yards', key: 'total_yards', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Yards per play', key: 'average_yards_per_play', fmt: 'dec2', opp: true, agg: 'ypp', yards: 'total_yards' },
        { label: 'Touchdowns', key: 'touchdowns', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'First downs', key: 'first_downs', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Drives', key: 'number_of_drives', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Time of possession', key: 'time_of_possession', fmt: 'clock', opp: true, agg: 'sum' },
        { label: 'Third down %', key: 'third_down_conversion_percentage', fmt: 'pct', opp: true, agg: 'rate', num: 'third_down_conversion_success', den: 'third_down_conversion_attempts' },
        { label: 'Third down conversions', key: 'third_down_conversion_success', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Third down attempts', key: 'third_down_conversion_attempts', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Fourth down %', key: 'fourth_down_conversion_percentage', fmt: 'pct', opp: true, agg: 'rate', num: 'fourth_down_conversion_success', den: 'fourth_down_conversion_attempts' },
        { label: 'Fourth down conversions', key: 'fourth_down_conversion_success', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Fourth down attempts', key: 'fourth_down_conversion_attempts', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Red zone %', key: 'red_zone_success_percentage', fmt: 'pct', opp: true, agg: 'rate', num: 'red_zone_successes', den: 'red_zone_attempts' },
        { label: 'Red zone scores', key: 'red_zone_successes', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Red zone trips', key: 'red_zone_attempts', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Largest lead', key: 'largest_lead', fmt: 'num', agg: 'max' },
        { label: 'Largest deficit', key: 'largest_deficit', fmt: 'num', agg: 'max' },
    ]],
    ['Turnovers', [
        { label: 'Turnover differential', key: 'turnover_differential', fmt: 'sgn', agg: 'sum' },
        { label: 'Turnovers forced', key: 'turnovers_forced', fmt: 'num', agg: 'sum' },
        { label: 'Turnovers committed', key: 'turnovers_lost', fmt: 'num', agg: 'sum' },
        { label: 'Interceptions forced', key: 'interceptions_forced', fmt: 'num', agg: 'sum' },
        { label: 'Interceptions thrown', key: 'interceptions_lost', fmt: 'num', agg: 'sum' },
        { label: 'Fumbles forced', key: 'fumbles_forced', fmt: 'num', agg: 'sum' },
        { label: 'Fumbles lost', key: 'fumbles_lost', fmt: 'num', agg: 'sum' },
        { label: 'Pick sixes forced', key: 'pick_sixes_forced', fmt: 'num', agg: 'sum' },
        { label: 'Pick sixes thrown', key: 'pick_sixes_thrown', fmt: 'num', agg: 'sum' },
        { label: 'Scoop-and-scores', key: 'fumble_return_tds_forced', fmt: 'num', agg: 'sum' },
        { label: 'Fumble-return touchdowns allowed', key: 'fumble_return_tds_committed', fmt: 'num', agg: 'sum' },
        { label: 'Touchdowns off turnovers', key: 'turnover_touchdowns_forced', fmt: 'num', agg: 'sum' },
        { label: 'Turnover touchdowns allowed', key: 'turnover_touchdowns_lost', fmt: 'num', agg: 'sum' },
    ]],
    ['Defense', [
        { label: 'Sacks forced', key: 'sacks_forced', fmt: 'num', agg: 'sum' },
        { label: 'Safeties forced', key: 'safeties_forced', fmt: 'num', agg: 'sum' },
        { label: 'Safeties committed', key: 'safeties_committed', fmt: 'num', agg: 'sum' },
        { label: 'Blocked field goals', key: 'blocked_opponent_field_goals', fmt: 'num', agg: 'sum' },
        { label: 'Blocked punts', key: 'blocked_opponent_punt', fmt: 'num', agg: 'sum' },
        { label: 'Kick sixes forced', key: 'opponent_field_goal_touchdown', fmt: 'num', agg: 'sum' },
        { label: 'Kick sixes allowed', key: 'field_goal_touchdown', fmt: 'num', agg: 'sum' },
    ]],
    ['Special teams', [
        { label: 'Field goals', fmt: 'fgratio', made: 'field_goal_made', att: 'field_goal_attempts', opp: true, agg: 'fgratio' },
        { label: 'Field goal %', key: 'field_goal_percentage', fmt: 'pct', opp: true, agg: 'rate', num: 'field_goal_made', den: 'field_goal_attempts' },
        { label: 'Longest field goal', key: 'longest_field_goal', fmt: 'num', opp: true, agg: 'max' },
        { label: 'Punts', key: 'punts_attempted', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Average punt length', key: 'average_punt_length', fmt: 'dec1', opp: true, agg: 'wavg', weight: 'punts_attempted' },
        { label: 'Longest punt', key: 'longest_punt', fmt: 'num', opp: true, agg: 'max' },
        { label: 'Kickoffs', key: 'number_of_kickoffs', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Touchbacks', key: 'touchbacks', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Touchback %', key: 'touchback_percentage', fmt: 'pct', opp: true, agg: 'rate', num: 'touchbacks', den: 'number_of_kickoffs' },
        { label: 'Onside attempts', key: 'onside_attempts', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Onside recoveries', key: 'onside_success', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Onside %', key: 'onside_success_percentage', fmt: 'pct', opp: true, agg: 'rate', num: 'onside_success', den: 'onside_attempts' },
        { label: 'Kick-return touchdowns', key: 'kick_return_td', fmt: 'num', opp: true, agg: 'sum' },
        { label: 'Punt-return touchdowns', key: 'punt_return_td', fmt: 'num', opp: true, agg: 'sum' },
    ]],
    ['Performance', [
        { label: 'Average difference', key: 'average_diff', fmt: 'dec1', agg: 'mean' },
        { label: 'Average offensive difference', key: 'average_offensive_diff', fmt: 'dec1', agg: 'mean' },
        { label: 'Average defensive difference', key: 'average_defensive_diff', fmt: 'dec1', agg: 'mean' },
        { label: 'Offensive special teams difference', key: 'average_offensive_special_teams_diff', fmt: 'dec1', agg: 'mean' },
        { label: 'Defensive special teams difference', key: 'average_defensive_special_teams_diff', fmt: 'dec1', agg: 'mean' },
        { label: 'Average response time', key: 'average_response_speed', fmt: 'clock', agg: 'mean' },
    ]],
];

export const STAT_ROWS = STAT_GROUPS.flatMap(([, rows]) => rows);
